spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Clip_Connect
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      springframework:
        security: DEBUG